-- Wrangler horses being trained for the guest string
insert into other_animals (name, group_name) values
  ('Xena',           'In Training'),
  ('Benny',          'In Training'),
  ('Palo',           'In Training'),
  ('Verde',          'In Training'),
  ('Lefty',          'In Training'),
  ('PayDay',         'In Training'),
  ('Joker',          'In Training'),
  ('Koga',           'In Training'),
  ('Nueve',          'In Training'),
  ('Indie',          'In Training'),
  ('Flint',          'In Training'),
  ('Journey',        'In Training'),
  ('Blitz',          'In Training'),
  ('Cowboy',         'In Training'),
  ('Juice',          'In Training'),
  ('New Paint Mare', 'In Training'),
  ('Benson',         'In Training'),
  ('Ace',            'In Training'),
  ('Mayo',           'In Training'),
  ('Jazzie',         'In Training'),
  ('Moab',           'In Training'),
  ('Aspen',          'In Training');
